name: Reusable Workflow To Deploy MuleSoft Application
 
on:
 push:
  branches: [ UAT ]

jobs:
  call-workflow:
    uses: Indrajith045/pipeline/.github/workflows/pipeline-uat.yml@main
    secrets: inherit
  
